### PR TITLE
[server][README]  Fix download link of hatohol.repo

### PR DESCRIPTION
**Pull request by Mnakagawa**

### CODE REVIEW

**Comment by bynnchapu** [comment]
[:+1:](http://www.lgtm.in/u/W3rtRRx7q)

**Comment by cosmo0920** [comment]
Good catch!

**Comment by Mnakagawa** [comment]
Do you know some link of as this fix?
Let's fix all old link!

**Comment by cosmo0920** [comment]
I found a wrong link for hatohol repository in `wercker/Dockerfile`.
I've already made the pull request #1193.

**Pull request merged**
