### PR TITLE
Support New travis CI

### PR DESCRIPTION
**Pull request by kz0817**
These patches fix problems on the new TravisCI infrastructure (since Dec. 2015).
Although we have still the following two problems, I send a PR once because almost all the issues are resolved.

1. Tests with clang still fail.
(@ashie is working on it now and will send the PR.)

2. test_syslogout() sometimes fails.

### CODE REVIEW

**Comment by cosmo0920** [comment]
Super cool! :heart_eyes:

**Comment by ashie** [comment]
Although some issues are remained, I merge this PR because it's better than before.

**Comment by ashie** [comment]
A HAP2 test is failed. Do you know the reason?

https://travis-ci.org/project-hatohol/hatohol/jobs/95955500

```
======================================================================
FAIL: test_normal_run (TestStandardHap.TestStandardHap)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/project-hatohol/hatohol/server/hap2/hatohol/test/TestStandardHap.py", line 103, in test_normal_run
    self.assertTrue(result_ms, exact_ms)
AssertionError: <haplib.MonitoringServerInfo instance at 0x16aad40>
----------------------------------------------------------------------
Ran 305 tests in 2.453s

FAILED (failures=1)
```

**Comment by kz0817** [comment]
> A HAP2 test is failed. Do you know the reason?

It would be fixed by the patch proposed as #1820.

**Pull request merged**
