### PR TITLE
[ConfigManager] Fix a bug that loads old events unexpectedly

### LINKED ISSUE #1057: [server] --load-old-eventsを指定していなくても古いイベントが読み込まれる
最近のmasterを自分の環境で使うと、 #915 で追加された`--load-old-events`を与えていなくても
古いイベントが読み込まれてしまう。

原因はConfigManagerのloadOldEventsが初期化されていないため。
未初期化変数が原因なので、環境によっては再現しないかも。

### PR DESCRIPTION
**Pull request by ashie**
Fix #1057

### CODE REVIEW

**Comment by kz0817** [comment]
Some tests on the Travis CI failed. It may be related with this fix or the fix in #915.
<pre>
===============================================================================

Failure: testArmZabbixAPI::test_getStubbedEventList

<expectedLastEventId - expectedFirstEventId + 1 == static_cast<uint64_t>(eventList.size())>

expected: <2987>

actual: <1>

./testArmZabbixAPI.cc:834: void testArmZabbixAPI::test_getStubbedEventList(): cppcut_assert_equal(expectedLastEventId - expectedFirstEventId + 1, static_cast<uint64_t>(eventList.size()), )

===============================================================================
</pre>

**Comment by ashie** [comment]
Oops, I'll investigate it.

**Comment by ashie** [comment]
I fixed broken tests but I think we should add more tests.
Please wait for a while.

**Comment by ashie** [comment]
> I've fixed broken tests but I think we should add more tests for #915.

I'll do it in another pull request.

**Pull request merged**
