### PR TITLE
Add hap2-common to server package required 

### PR DESCRIPTION
**Pull request by Mnakagawa**

### CODE REVIEW

**Comment by cosmo0920** [comment]
At least, let's wait for Wercker CI result.

**Comment by Mnakagawa** [comment]
Yes. I will

**Comment by cosmo0920** [comment]
Building rpm succeeded in Wercker. :shipit:!

**Comment by Mnakagawa** [comment]
OK
Please merge :)

**Comment by Mnakagawa** [comment]
Thanks

**Pull request merged**
