### PR TITLE
[doc] Remove obsolete documents under doc/server/manual

### PR DESCRIPTION
**Pull request by ashie**
We won't maintain them anymore.

### CODE REVIEW

**Comment by Mnakagawa** [comment]
All test were failed...

**Comment by cosmo0920** [comment]
These failure caused by ppa in fetching packages step....

**Comment by Mnakagawa** [comment]
The following URL is invalidness?
It is used in https://raw.githubusercontent.com/clear-code/cutter/master/data/travis/setup.sh

```
http://sourceforge.net/project/cutter/files
```

**Comment by cosmo0920** [comment]
No. Perhaps, gce apt repository cache is down.

```log
W: Failed to fetch http://us-central1.gce.archive.ubuntu.com/ubuntu/dists/precise/Release.gpg  Could not connect to us-central1.gce.archive.ubuntu.com:80 (199.223.234.73), connection timed out [IP: 199.223.234.73 80]
W: Failed to fetch http://us-central1.gce.archive.ubuntu.com/ubuntu/dists/precise-updates/Release.gpg  Unable to connect to us-central1.gce.archive.ubuntu.com:http: [IP: 199.223.234.73 80]
W: Failed to fetch http://us-central1.gce.archive.ubuntu.com/ubuntu/dists/precise-backports/Release.gpg  Unable to connect to us-central1.gce.archive.ubuntu.com:http: [IP: 199.223.234.73 80]
W: Some index files failed to download. They have been ignored, or old ones used instead.
E: Unable to correct problems, you have held broken packages.
```

**Comment by Mnakagawa** [comment]
Is this problem only temporary?
If so, I merge this PR.

**Comment by cosmo0920** [comment]
Yes, this issue seems to be temporary.

**Comment by Mnakagawa** [comment]
Thank you:+1:

**Pull request merged**
