### PR TITLE
[EventsView] Don't show .incidentCheckbox when the feature is disabled or conflicts

### PR DESCRIPTION
**Pull request by ashie**
issue #2191

### CODE REVIEW

**Comment by ashie** [comment]
In addition, remove following obsolete liens:

```diff
-      $("#IncidentTypeHatoholNotAssignedEventLabel").show();
-      $("#IncidentTypeHatoholImportantEventLabel").show();
-      $("#IncidentTypeHatoholImportantEventProgress").show();
```

**Comment by cosmo0920** [comment]
> In addition, remove following obsolete liens:

Should we split commits into 2 commits which are adding feature and removing obsoleted lines?
Or, all-in-one commit is acceptable?

**Comment by ashie** [comment]
Please decide as you like.

**Comment by cosmo0920** [comment]
I decided to merge this PR as is.

**Pull request merged**
