### PR TITLE
Upgrade JavaScript libraries

### PR DESCRIPTION
**Pull request by hrk141**
Upgrade:

name | old | new
--- | --- | ---
bootstrap | 3.1.0 | 3.3.6
jquery | 1.9.1 | 2.1.4
multiselect | 2.1.1 | 2.1.4
jquer-ui-slider-pips | 1.7.2 | 1.10.8

Not modified:

name | ver | reason
--- | --- | ---
jquery-deparam | - | latest
jquery-ui | 1.10.2 | on hold
datetimepicker | 2.4.5 | latest
flot | 0.8.3 | latest
spectrum | 1.7.1 | latest

### CODE REVIEW

**Comment by cosmo0920** [comment]
This patch makes not to be able to execute browser test. :cold_sweat: 
Could you fix it?

```log
 $(npm bin)/mocha-phantomjs http://localhost:8000/test/index.html
Error loading resource http://localhost:8000/static/js.external/jquery.js (203). Details: Error downloading http://localhost:8000/static/js.external/jquery.js - server replied: NOT FOUND
Error loading resource http://localhost:8000/static/js.external/multiselect.js (203). Details: Error downloading http://localhost:8000/static/js.external/multiselect.js - server replied: NOT FOUND
Error loading resource http://localhost:8000/static/js.external/bootstrap.js (203). Details: Error downloading http://localhost:8000/static/js.external/bootstrap.js - server replied: NOT FOUND
ReferenceError: Can't find variable: jQuery

  http://localhost:8000/static/js.external/jquery-ui.min.js:5
```

**Comment by cosmo0920** [comment]
I've added to follow upgrading JavaScript changes: https://github.com/project-hatohol/hatohol/compare/9b21c1e407...3340b71a56.
Now, all client browser tests are green!

```log
% $(npm bin)/mocha-phantomjs http://localhost:8000/test/index.html


  HatoholSessionManager
    ✓ get
    ✓ set

  HatoholConnector
    ✓ get simplest (56ms)
    ✓ post simple
    ✓ specify pathPrefix
Error loading resource http://localhost:8000/tunnel/test (202). Details: Error downloading http://localhost:8000/tunnel/test - server replied: FORBIDDEN
    ✓ connection error callback
    ✓ parse error callback
    ✓ specify replyParser
    ✓ completion callback
Error loading resource http://localhost:8000/tunnel/X (299). Details: Error downloading http://localhost:8000/tunnel/X - server replied: INTERNAL SERVER ERROR
    ✓ completion callback after error
    ✓ specify context in replyCallback
Error loading resource http://localhost:8000/tunnel/X (299). Details: Error downloading http://localhost:8000/tunnel/X - server replied: INTERNAL SERVER ERROR
    ✓ specify context in connectErrorCallback
    ✓ specify context in completionCallback
    ✓ get simplest twice with reusing it

  HatoholReplyParser
    ✓ null
    ✓ undefined
    ✓ not found apiVersion
    ✓ not support API version
    ✓ not found errorCode
    ✓ errorCode is not OK
    ✓ get error code
    ✓ get error code name
    ✓ use a pre-defined message
    ✓ use a server's message
    ✓ without a message
    ✓ use a option message

  HatoholLoginReplyParser
    ✓ no sessionId

  HatoholMessageBox
    ✓ passes only the first (message) argument
    ✓ specify the title
    ✓ specify the defaultButtonLabel
    ✓ specify ID
    ✓ specify buttons
    ✓ get builtin NO/YES buttons
    ✓ confirm builtin NO/YES buttons are deeply copied
    ✓ hatoholMsgBoxForParser on a status error
    ✓ hatoholMsgBoxForParser on a server error

  HatoholUserConfig
    ✓ try to get nonexisting item
    ✓ store a string (55ms)
    ✓ store an integer (50ms)
    ✓ store an float (58ms)
    ✓ store a boolean (58ms)
    ✓ store null (59ms)
    ✓ store and get a string (76ms)
    ✓ store and get an integer (67ms)
    ✓ store and get a float (66ms)
    ✓ store and get a boolean (67ms)
    ✓ store and get null (66ms)
    ✓ store multiple value and get them (81ms)
    ✓ store multiple value and get them with the non-existent (68ms)

  HatoholNavi
    ✓ show users against admin
    ✓ do not show users against guest
    ✓ with no current page
    ✓ with a current page argument

  HatoholPager
    ✓ do not show
    ✓ create with 100 records
    ✓ create with 101 records
    ✓ 0 records per page
    ✓ 0 records per page agaist 0 total records
    ✓ negative value for number of records per page
    ✓ 6 / 20 pages
    ✓ 7 / 20 pages
    ✓ 15 / 20 pages
    ✓ 16 / 20 pages
    ✓ 17 / 20 pages
    ✓ 6 / 6 pages

  HatoholUserProfile
    ✓ load user
    ✓ show user name
    ✓ change password callback should be set (40ms)
    ✓ logout

  HatoholUserRolesEditor
    ✓ new

  HatoholUserEditDialog
    ✓ new with empty params
    ✓ new with admin user data
    ✓ click apply button

  HatoholIncidentTrackerEditor
    ✓ new
    ✓ change to Hatohol incident tracker type

  EventsViewConfig
[http://localhost:8000/ajax_events?start=false:790] TypeError: 'undefined' is not an object (evaluating 'userProfile.addOnLoadCb')
    ✓ load on create (116ms)
    ✓ getCurrentFilterConfig with empty data
    ✓ set and get current filter
    ✓ convert filter config to filter

  HatoholModal
    ✓ new
    ✓ with title
    ✓ with footer
    ✓ with body

  Utils
    isFloat
      ✓ 0 (number)
      ✓ 0.0 (number)
      ✓ 0.0 (string)
      ✓ 1 (number)
      ✓ 1.0 (number)
      ✓ 1.0 (string)
    isInt
      ✓ 1
      ✓ 1.1
    getServerLocation
      ✓ with valid zabbix server
      ✓ zabbix server with port
      ✓ ipv6 zabbix server
      ✓ with valid nagios server
      ✓ nagios server with port
      ✓ nagios server with baseURL
      ✓ ipv6 nagios server
      ✓ with valid HAPI zabbix server
      ✓ HAPI zabbix server with port
      ✓ ipv6 HAPI zabbix server
      ✓ with HAPI JSON type(unknown)
      ✓ with HAPI CEILOMETER type(unknown)
      ✓ with unknown server type
    getItemGraphLocation
      ✓ with valid zabbix server
      ✓ with valid nagios server
      ✓ with valid HAPI zabbix server
      ✓ with valid HAPI JSON
      ✓ with valid HAPI CEILOMETER
      ✓ with unknown server type
    getMapsLocation
      ✓ with valid zabbix server
      ✓ with valid nagios server
      ✓ with valid HAPI zabbix server
      ✓ with valid HAPI JSON(unknown)
      ✓ with valid HAPI CEILOMETER(unknown)
      ✓ with unknown server type
    makeMonitoringSystemTypeLabel
      ✓ with valid zabbix server
      ✓ with valid nagios server
      ✓ with valid HAPI zabbix server
      ✓ with valid HAPI JSON
      ✓ with valid HAPI CEILOMETER
      ✓ with unknown server type
    getHostName
      ✓ with valid name
      ✓ with no server
      ✓ with no host
      ✓ plugin dependent
      ✓ plugin dependent returns null
    getNickName
      ✓ with valid nickname
      ✓ with no server
      ✓ with no nickname
    getHostgroupName
      ✓ with valid name
      ✓ with no server
      ✓ with no hostgroup
    getTriggerBrief
      ✓ with valid name
      ✓ with no server
      ✓ with no trigger
    deparam
      ✓ 1 param
      ✓ empty value
      ✓ empty key
      ✓ zero as key
      ✓ decode
      ✓ complex object
    formatItemValue
      ✓ Text
      ✓ Integer without unit
      ✓ Integer with unit
      ✓ Integer without metric prefix
      ✓ Integer with metric prefix
      ✓ Float without unit
      ✓ Float with trailing 0
      ✓ Large float
      ✓ Percent
      ✓ uptime less than one day
      ✓ uptime with one day
      ✓ uptime with two days
      ✓ Kilo Bytes
      ✓ Mega Bytes
      ✓ Giga Bytes
    plugin
      ✓ getServerLocation
      ✓ getServerLocation without plugin function
      ✓ getMapsLocation
      ✓ getMapsLocation without plugin function
      ✓ getItemGraphLocation
      ✓ getItemGraphLocation without plugin function
      ✓ makeMonitoringSystemTypeLabel
    flag
      ✓ hasFlag under 31bit
      ✓ hasFlag 31bit
      ✓ hasFlag 32bit
      ✓ hasFlag over 32bit
      ✓ addFlag
    flags
      ✓ hasFlags

  HatoholMonitoringView
    ✓ set filter candidates
    ✓ set filter candidates with a string array
    ✓ set empty filter
    ✓ setupHostQuerySelector: select server
    ✓ setupHostQuerySelector: select host group
    ✓ setupHostQuerySelector: select host
    ✓ setupHostQuerySelector: select application
    ✓ soon after calling setupCheckboxForDelete
    ✓ not show check boxes if the user does not have the privilege
    ✓ activity of the delete button by check box status.

  ServerView
[http://localhost:8000/ajax_servers?start=false:217] TypeError: 'undefined' is not an object (evaluating 'userProfile.addOnLoadCb')
    ✓ pass an undefined packet
    ✓ pass an undefined serverConnStat
    ✓ set nonexisting server id
    ✓ set existing server id
    ✓ get status label before calling setServerId()
    ✓ get status label with no status member
    ✓ get status label at initial state
    ✓ get status label at OK state
    ✓ get status label at Error state
    ✓ get status label at unknown state
    ✓ get info HTML before calling setServerId
    ✓ get info HTML
    ✓ with delete privilege (63ms)
    ✓ with delete_all privilege
    ✓ with no delete privilege
    ✓ with update privilege
    ✓ with all update privilege
    ✓ without update privilege
    ✓ without update privilege

  EventsView
[http://localhost:8000/ajax_events?start=false:790] TypeError: 'undefined' is not an object (evaluating 'userProfile.addOnLoadCb')
    ✓ new with empty data (82ms)
    ✓ new with fake zabbix data (51ms)
    ✓ new with fake zabbix data included expanded description (51ms)
    ✓ new with nagios data without baseURL (73ms)
    ✓ new with nagios data included baseURL (58ms)
    ✓ With a good event (54ms)
    ✓ Default columns (47ms)
    ✓ Customize columns (55ms)
    ✓ Treatment columns (47ms)
    ✓ Treatment user-defined label columns (56ms)

  UsersView
[http://localhost:8000/ajax_users?start=false:206] TypeError: 'undefined' is not an object (evaluating 'userProfile.addOnLoadCb')
    ✓ Base elements
    ✓ with delete privilege
    ✓ with no delete privilege

  ActionsView
[http://localhost:8000/ajax_actions?start=false:211] TypeError: 'undefined' is not an object (evaluating 'userProfile.addOnLoadCb')
    ✓ Base elements
    ✓ with delete privilege
    ✓ with delete_all privilege
    ✓ with no delete privilege
    ✓ with update privilege
    ✓ with all update privilege
    ✓ with no update privilege

  IncidentSettingsView
[http://localhost:8000/ajax_incident_settings?start=false:209] TypeError: 'undefined' is not an object (evaluating 'userProfile.addOnLoadCb')
    ✓ Base elements
    ✓ with delete privilege
    ✓ with no delete privilege
    ✓ with update privilege
    ✓ with no update privilege

  LatestView
[http://localhost:8000/ajax_latest?start=false:216] TypeError: 'undefined' is not an object (evaluating 'userProfile.addOnLoadCb')
    ✓ new with empty data
    ✓ Float item
    ✓ String item
    ✓ default page size

  OverviewItems
[http://localhost:8000/ajax_overview_items?start=false:196] TypeError: 'undefined' is not an object (evaluating 'userProfile.addOnLoadCb')
    ✓ new with empty data
    ✓ With items

  HistoryView
[http://localhost:8000/ajax_history?start=false:246] TypeError: 'undefined' is not an object (evaluating 'userProfile.addOnLoadCb')
    ✓ load history with time range (147ms)
    ✓ load history without time range (77ms)
    ✓ format graph data (95ms)
    ✓ parse multiple items query
    ✓ get config from item selector

  LogSearchSystemsView
[http://localhost:8000/ajax_log_search_systems?start=false:204] TypeError: 'undefined' is not an object (evaluating 'userProfile.addOnLoadCb')
    ✓ Base elements

  GraphsView
[http://localhost:8000/ajax_graphs?start=false:198] TypeError: 'undefined' is not an object (evaluating 'userProfile.addOnLoadCb')
    ✓ Base elements
    ✓ load a graph setting

  TriggersView
[http://localhost:8000/ajax_triggers?start=false:220] TypeError: 'undefined' is not an object (evaluating 'userProfile.addOnLoadCb')
    ✓ new with empty data
    ✓ Base elements
    ✓ Without expandedDesctription
    ✓ With expandedDesctription
    ✓ With a problem trigger

  hap2_fluentd
    ✓ getHostName

  hap2_ceilometer
    ✓ getHostName: N/A
    ✓ getHostName: normal strings

  hap2_zabbix
    ✓ getTopURL
    ✓ getTopURL with unknown suffix
    ✓ getMapsURL
    ✓ getItemGraphURL

  SeverityRanksView
[http://localhost:8000/ajax_severity_ranks?start=false:180] TypeError: 'undefined' is not an object (evaluating 'userProfile.addOnLoadCb')
    ✓ Base elements
    ✓ with update privilege
    ✓ with no update privilege

  CustomIncidentLabelsView
[http://localhost:8000/ajax_custom_incident_labels?start=false:178] TypeError: 'undefined' is not an object (evaluating 'userProfile.addOnLoadCb')
    ✓ Base elements
    ✓ with update privilege
    ✓ with no update privilege


  256 passing (7s)
```

**Comment by kz0817** [comment]
> Now, all client browser tests are green!

Great!

**Comment by cosmo0920** [comment]
Thanks!

**Pull request merged**
