### PR TITLE
[client][test][feature] Add assertions and more reduce magic numbers for waiting CSS selectors

### PR DESCRIPTION
**Pull request by cosmo0920**
I added assertions for:
* add/delete operations

Edit assertion and its test are not implemented yet.

And I reduced magic numbers for waiting CSS selectors.

### CODE REVIEW

**Comment by ashie** [comment]
Sometimes the following error occurs both on Travis CI and on my environment.
```
FAIL Registered incident setting's server name "test-zabbix" exists in the incident settings table.
# type: assertTextExists
# file: /home/travis/build/project-hatohol/hatohol/client/test/feature/register_incident_setting_test.js:99
# code: "\" exists in the incident settings table.");
# subject: false
# text: "test-zabbix"
```

**Comment by cosmo0920** [comment]
Hmm, I wonder why incident setting assertion test is too fragile.

For now, I decide to be disable this test. I gave up. :<

**Comment by ashie** [comment]
> For now, I decide to be disable this test. I gave up. :<

私の方で一度修正にチャレンジしてからマージしようと思ってましたが、いつになるか
分からないのでいったんマージします。

**Comment by cosmo0920** [comment]
あざっす！

**Pull request merged**
