### PR TITLE
Add the process of setting ”validity” to host registration of NagiosNDOUtils.

### PR DESCRIPTION
**Pull request by o-wakabayashi**
Dealing with issue #993 .

### CODE REVIEW

**Comment by ashie** [comment]
I think this modification itself is no problem.
But it conflicts with a big pull request #981.
Please wait for a while until merging it.

**Comment by o-wakabayashi** [comment]
Thank you for Confirmation.
I found in a other work, so it is not in a hurry.
But, worry whether there is same problem in commercial version.

**Comment by ashie** [comment]
I merged it because  #981 is closed.

**Comment by o-wakabayashi** [comment]
thank you for marged.
（存在を忘れてた、、、）

2015-02-20 10:53 GMT+09:00 Takuro Ashie <notifications@github.com>:

**Pull request merged**
