### PR TITLE
[server] Save IncidentStatusHitory after creating/updating incidents

### PR DESCRIPTION
**Pull request by ashie**
To track all changes of incidents.

Revise #2113

### CODE REVIEW

**Comment by cosmo0920** [comment]
It would be nice to use `nullptr` where `void *userData = NULL` and `IncidentInfo *incident = NULL`.
C++11 permits writing NULL as null pointer for backward compatibility but it provides `nullptr` keyword to distinguish between NULL and null pointer.
We should use `nullptr` keyword for null pointer.

**Comment by cosmo0920** [comment]
Otherwise it looks good to me! :smiley:

**Comment by cosmo0920** [comment]
Can we merge this PR?

Using `nullptr` is just a suggestion. it is not mandatory for merging this PR.

**Comment by ashie** [comment]
> Using nullptr is just a suggestion. it is not mandatory for merging this PR.

It should be another PR.

**Comment by cosmo0920** [comment]
>> Using nullptr is just a suggestion. it is not mandatory for merging this PR.

> It should be another PR.

OK. It makes more consistency for this PR. Let's merge this PR as-is!

**Pull request merged**
