### PR TITLE
Logging hap2 plugins msg #1738 2

### PR DESCRIPTION
**Pull request by kz0817**
These patches enables HAP2 plugins launched by Hatohol server to log their messages with syslog.

### CODE REVIEW

**Comment by kz0817** [comment]
It seems build failure. I check it soon.

**Comment by cosmo0920** [comment]
It seems to be packaging issue.

Wercker says rpmbuild failure.
Travis CI says make dist failure.

**Comment by ashie** [comment]
"distcheck" is failed.

https://travis-ci.org/project-hatohol/hatohol/jobs/91782211

Probably you need to add hap2-logging.conf to EXTRA_DIST.

**Comment by kz0817** [comment]
I fixed and sent the PR as #1750.
I close this issue.

**Pull request closed without merging**
