### PR TITLE
[EventsView] Add default filter config & filter chooser

### PR DESCRIPTION
**Pull request by ashie**
Default filter:

default-filter

Filter chooser:

filter-chooser

### CODE REVIEW

**Comment by ashie** [comment]
Now they are enabled by default.
You don't need "?devel=true" to see it any more.

**Comment by kz0817** [comment]
I met the following error. Is this due to the update from a development version to another development version ?
<pre>
$ PATH=hap/.libs:$PATH LD_LIBRARY_PATH=mlpl/src/.libs:src/.libs:common/.libs:hap/.libs src/.libs/hatohol --pid-file ~/tmp/hatohol.pid --foreground
[INFO] <main.cc:217> started hatohol server: ver. 15.07_dev1
[INFO] <DBTables.cc:203> DBTables 16 is outdated, try to update it ...
        old-version: 00.16 [00]
        new-version: 00.18 [00]
[CRIT] <main.cc:175> Failed to create a database object. This program is aborted. Reason: <DBAgentMySQL.cc:667> Failed to query: ALTER TABLE severity_ranks ADD COLUMN label VARCHAR(255) NOT NULL, ADD COLUMN as_important INT(11) NOT NULL DEFAULT 1: (1060) Duplicate column name 'label'
</pre>

**Comment by ashie** [comment]
> Is this due to the update from a development version to another development version ?

Probably, yes it is.
I also upgraded  the DB using this code, but it's successfully completed.

But we should check it again. I'll do it later.

**Comment by kz0817** [comment]
Once I dropped the database 'hatohol' and did hatohol-db-initiator, this branch of hatohol ran successfully. Thank for the comment.

**Comment by ashie** [comment]
Thanks!

**Pull request merged**
