### PR TITLE
[HatoholAddActionDialog] Enable to select trigger status on setting i…

### PR DESCRIPTION
**Pull request by ashie**
…ncident sender

Because not only TRIGGER_STATUS_PROBLEM but also
TRIGGER_STATUS_OK should be confirmed by human in most sites.

### CODE REVIEW

**Comment by cosmo0920** [comment]
If users use Redmine backend incident server, they should be able to select normal status?

**Comment by ashie** [comment]
Yes.

**Comment by cosmo0920** [comment]
Looks good. :+1:

**Comment by ashie** [comment]
Thanks!

**Pull request merged**
