### PR TITLE
[experimental] wercker: Try to add Wercker to build CentOS 6.x series

### PR DESCRIPTION
**Pull request by cosmo0920**
This pull request contains **experimental feature** for CI with CentOS 6.x series.

I found that `Wercker` supports Docker backend. ref: http://devcenter.wercker.com/articles/docker/
Docker backend makes for us to running various containers under `Wercker` CI environment!
That is, CentOS 6.x Docker container can run under `Wercker` Docker backend. :laughing: 

CI with Docker container (CentOS6.6) runs like this:
https://app.wercker.com/#build/54fd95a782ba1add4201ae34

`Wercker`'s worker running limit is 25 minutes.
So this wercker.yml and Dockerfile is only for building `Hatohol` server and web frontend.

For now, `Wercker`'s Docker feature seems to be *beta* feature, though. :<

### CODE REVIEW

**Comment by cosmo0920** [comment]
`Wercker` is currently beta status. This is sometimes broken when setting up build environment.
Please feel free to reject this pull request.

**Comment by cosmo0920** [comment]
Using temporary branch, Wercker test (only building on CentOS container) passed: https://app.wercker.com/#build/54fec0ee82ba1add420a6a2a

**Comment by bynnchapu** [comment]
I have a question.

It seems that this branch works build only.
Will you run test process (Cutter) in the future ?

**Comment by cosmo0920** [comment]
Yes, this branch intends to build only.
Just confirmation for building on CentOS 6.x.

**Comment by cosmo0920** [comment]
And Wercker worker running limit is 25 minutes.
It is hard to build and run tests by this running limit.

**Comment by cosmo0920** [comment]
> It seems that this branch works build only.
Will you run test process (Cutter) in the future ?

Ah, you mean that why not running Hatohol tests entirely in Wercker?
If so, my answer is No.
This is over testing and definitely excess of Wercker's worker running limit.

This pull request intents building Hatohol only on CentOS 6.x.
But, it is reasonable to build Hatohol server and tests code, I think.

**Comment by ashie** [comment]
I registered the application:

https://app.wercker.com/#applications/54feb63782ba1add4209e70f

**Comment by ashie** [comment]
> Wercker is currently beta status. This is sometimes broken when setting up build environment.
> Please feel free to reject this pull request.

It seems nice service.
I want to try it with the master branch, so I'll merge it.

**Comment by cosmo0920** [comment]
Thank you for merging!

I think `Werkcer` is nice service, too!
`Wercker` is also used by [serverspec](https://github.com/serverspec/serverspec) project.
I learned about it on the `serverspec` project.

**Comment by ashie** [comment]
> I registered the application:
> 
> https://app.wercker.com/#applications/54feb63782ba1add4209e70f

@bynnchapu If you want to change the settings, please sign up & tell me your account name.

**Pull request merged**
