### PR TITLE
[WebUI][EventsView] Initial implementation of the user comments feature

### PR DESCRIPTION
**Pull request by ashie**
Issue #2119

### CODE REVIEW

**Comment by ashie** [comment]
Some issues are still remained: #2167

**Comment by cosmo0920** [comment]
:+1: 
It works well with https://github.com/project-hatohol/hatohol/pull/2186 included hatohol server.

Can I merge this?

**Comment by ashie** [comment]
plz

**Comment by cosmo0920** [comment]
I've merged it!

**Comment by ashie** [comment]
Thanks!

**Pull request merged**
