### PR TITLE
[hap2] Create new nagios plugin that use livestatus API

### PR DESCRIPTION
**Pull request by Mnakagawa**
livestatus API:
https://mathias-kettner.de/checkmk_livestatus.html

CentOS(from epel repository)
```
# yum install check-mk-livestatus
```

Ubuntu
```
# apt-get install check-mk-livestatus
```

Python library:
https://github.com/arthru/python-mk-livestatus
CentOS & Ubuntu
```
# pip install python-mk-livestatus
```

### CODE REVIEW

**Comment by cosmo0920** [comment]
hap2 test failing:

```log
======================================================================
ERROR: TestHap2NagiosLivestatus (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: TestHap2NagiosLivestatus
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/loader.py", line 252, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python2.7/unittest/loader.py", line 230, in _get_module_from_name
    __import__(name)
  File "/home/travis/build/project-hatohol/hatohol/server/hap2/hatohol/test/TestHap2NagiosLivestatus.py", line 28, in <module>
    from hap2_nagios_livestatus import Common
  File "/home/travis/build/project-hatohol/hatohol/server/hap2/hatohol/hap2_nagios_livestatus.py", line 33, in <module>
    from mk_livestatus import Socket
ImportError: No module named mk_livestatus
----------------------------------------------------------------------
```

Could you fix it?

**Comment by cosmo0920** [comment]
Ah, perhaps you should fix `.travis.yml` to pass these live status hap2 tests.

**Comment by cosmo0920** [comment]
If you add `python-mk-livestatus` installation on Travis, you might have to instal via apt instead of pip.
Because this nagios plugin written in C/C++.

**Comment by cosmo0920** [comment]
I tried to run livestatus plugin tests in this branch:
https://github.com/project-hatohol/hatohol/compare/create-nagios-livestatus-plugin-4-travis

But livestatus plugin tests didn't pass:
https://travis-ci.org/project-hatohol/hatohol/jobs/98633863

Could you fix failing tests?

**Comment by Mnakagawa** [comment]
The test does not need to check-mk-livestatus libraly.
make_afunix_socket.py works as check-mk-livestatus plugin.

Reason of failure is can not to find make_afunix_socket.py.
I fixed this problem.

**Comment by Mnakagawa** [comment]
If success the test in travis, I rebase and create new PR

**Comment by cosmo0920** [comment]
> If success the test in travis, I rebase and create new PR

hap2 tests are all green in Travis now. Let's rebase and create the new PR wit hrebased branch!

**Comment by Mnakagawa** [comment]
Thank you for your check!

**Pull request closed without merging**
