### PR TITLE
[client] Add no-cache headers in response

### PR DESCRIPTION
**Pull request by cosmo0920**
* Django 1.5: https://docs.djangoproject.com/en/1.5/ref/request-response/#setting-headers

#979

### CODE REVIEW

**Comment by kz0817** [comment]
Is there any reason that "Pragma" and "Expires" are not set in python code ?

**Comment by cosmo0920** [comment]
It is no reason that "Pragma" and "Expires" are not to set in python code.
It is just forgot it.

**Comment by kz0817** [comment]
I confirmed that the added ones were in the header. 
tunnel

**Comment by cosmo0920** [comment]
Thanks!

**Pull request merged**
