### PR TITLE
Work for splitting #2370 revert 2

### PR DESCRIPTION
**Pull request by kz0817**
As reported in https://github.com/project-hatohol/hatohol/pull/2316,
The patch set breaks user fileter.

Note that date-time and some line information in djangojs.po conflicted.
They are just meta data and don't change behavior though.
I take the ones of HEAD.

### CODE REVIEW

**Comment by ashie** [comment]
It's not for master, it's for work-for-splitting-#2370, isn't it?
I changed the base branch to work-for-splitting-#2370...

**Comment by kz0817** [comment]
> It's not for master, it's for work-for-splitting-#2370, isn't it?

Yes, it's for work-for-splitting-#2370.

> I changed the base branch to work-for-splitting-#2370...

Thank you.

**Comment by cosmo0920** [comment]
Looks good. :+1:

**Comment by kz0817** [comment]
Thank you.

**Pull request merged**
