### PR TITLE
[client][js][event_view] Dynamic change events to click sammary button

### PR DESCRIPTION
**Pull request by Mnakagawa**
And fix js.po.

### CODE REVIEW

**Comment by cosmo0920** [comment]
screenshot from 2016-05-24 14 57 24

Unhandled Important Events and Important events text seems to be swapped.
Is this intended behaviour?
screenshot from 2016-05-24 14 57 39


screenshot from 2016-05-24 14 57 57

**Comment by cosmo0920** [comment]
:+1:

**Comment by cosmo0920** [comment]
Can I merge this?

**Comment by Mnakagawa** [comment]
OK. Please!

**Comment by Mnakagawa** [comment]
Thanks!

**Comment by Mnakagawa** [comment]
This patch has many bugs...
User filter does not work correctly.
So, we should revert this.

**Comment by cosmo0920** [comment]
> This patch has many bugs...
User filter does not work correctly.

:scream:

**Pull request merged**
