### PR TITLE
[server] Register a host for self monitor (#1836).

### PR DESCRIPTION
**Pull request by kz0817**
Previously, the host name is not correctly shown in WebUI.
This patch shows it as "(self-monitor)".

### CODE REVIEW

**Comment by cosmo0920** [comment]
:+1:

**Comment by cosmo0920** [comment]
Oh, HAPI2 related test are failing https://travis-ci.org/project-hatohol/hatohol/jobs/97591985 :

```log
Failure: testHatoholArmPluginGateHAPI2::testProcedureHandlers::test_procedureHandlerPutHostsInvalidJSON
<hostDefVect.size() == static_cast<size_t>(0)>
expected: <1>
  actual: <0>
test/../server/test/testHatoholArmPluginGateHAPI2.cc:645: void testHatoholArmPluginGateHAPI2::testProcedureHandlers::test_procedureHandlerPutHostsInvalidJSON(): cppcut_assert_equal(hostDefVect.size(), static_cast<size_t>(0), )
...
Failure: testHatoholArmPluginGateHAPI2::testProcedureHandlers::test_procedureHandlerPutHosts
<expectedOutput == actualOutput>
expected: <"1|#ANY#|302|1|exampleHostName1|0
">
  actual: <"1|#ANY#|302|__SELF_MONITOR|(self-monitor)|0
1|#ANY#|302|1|exampleHostName1|0
">
diff:
+ "1|#ANY#|302|__SELF_MONITOR|(self-monitor)|0
? "1|#ANY#|302|1|exampleHostName1|0
  "
test/../server/test/testHatoholArmPluginGateHAPI2.cc:614: void testHatoholArmPluginGateHAPI2::testProcedureHandlers::test_procedureHandlerPutHosts(): cppcut_assert_equal(expectedOutput, actualOutput, )
```

**Comment by kz0817** [comment]
Oops. I'll fix it.

**Comment by kz0817** [comment]
I fixed the broken tests.

**Comment by cosmo0920** [comment]
:+1: again.

@ashie Any concerns?

**Comment by ashie** [comment]
:+1:

**Pull request merged**
