### PR TITLE
[EventsView] Fix labels of filter candidates

### PR DESCRIPTION
**Pull request by ashie**
Fix following bugs and simplify the code:

* Labels of severities aren't set to filter menu.
* Values of incidents aren't set to filter menu when they are failed to load.

### CODE REVIEW

**Comment by cosmo0920** [comment]
Wercker complains unpackaged files existing: 

```log
Checking for unpackaged file(s): /usr/lib/rpm/check-files /root/rpmbuild/BUILDROOT/hatohol-16.01_alpha1-1.el6.x86_64
error: Installed (but unpackaged) file(s) found:
/usr/share/hatohol/sql/actions.sql
/usr/share/hatohol/sql/incident-trackers.sql
```

**Comment by ashie** [comment]
> Wercker complains unpackaged files existing:

FIx it in #1867

**Comment by cosmo0920** [comment]
:+1:

**Comment by ashie** [comment]
Thanks!

**Pull request merged**
