### PR TITLE
[Travis] Switch to use gcc-4.8.x series in Travis

### PR DESCRIPTION
**Pull request by cosmo0920**
Travis CI cpp instance's default gcc is 4.6.
This pull request intents to use gcc-4.8.x series in Travis CI. 

Related to #1186.

### CODE REVIEW

**Comment by kz0817** [comment]
Before merging this patch, we want to summarize the impact of using new GCC with C++11 features as a default especially on CentOS6/7 at runtime.

Do we need to install additional libraries ?

**Comment by cosmo0920** [comment]
> Do we need to install additional libraries ?

Yes, we do. But we need to do for a few old environment.

I think that Ubuntu 12.04 LTS (used by Travis CI) and CentOS 6.x are needed additional runtime library for gcc-4.8.
We need to install additional libraries which are `libstdc++4.8-dev` in Ubuntu Precise (12.04 LTS).
We need to install additional libraries which are `devtoolset-2-runtime` in CentOS 6.x.

CentOS 7.x's and Ubuntu Trusty(14.04 LTS)'s default is gcc 4.8. 
So, we needn't to do anything, though.

**Comment by kz0817** [comment]
Thank you for the reply.
I'll merge the Pull Request.

**Comment by cosmo0920** [comment]
Thanks!

**Pull request merged**
