### PR TITLE
Add an abstract class for the transporter layer on HAPI2.0.

### PR DESCRIPTION
**Pull request by kz0817**

### CODE REVIEW

**Comment by cosmo0920** [comment]
It seems that running hap2 tests settings is missing in `.travis.yml`.
Adding running hap2 test in Travis CI is planned to another pull request?

**Comment by kz0817** [comment]
Thank you for the comment.
I forget to modify the .travis.yml.
I'll do it soon.

**Comment by kz0817** [comment]
I'm done. Please check it again.

**Comment by kz0817** [comment]
THX

**Pull request merged**
