### PR TITLE
[zabbixapi] Consider about $ macro is not digit

### PR DESCRIPTION
**Pull request by Mnakagawa**
Related: #2341

### CODE REVIEW

**Comment by cosmo0920** [comment]
Looks good.
Could you check this, @bynnchapu ?

**Comment by bynnchapu** [comment]
OK. I'll check the code and behavior.

**Comment by bynnchapu** [comment]
It seems code is good.
But, now I'm trying to create testing environment although, I can not add monitoring server using HAPI2...

I think it takes time to check behavior...
Please wait a little.

**Comment by bynnchapu** [comment]
I've tried in the problem environment.
It seems the error log which is output in #2341 is not output but, other message is output:

```
python[20594]: hap.py:96 hatohol.hap:hap2_zabbix_api.py:Poller: [20594]: [ERROR] Unexpected error: <type 'exceptions.AssertionError'>,
                Traceback (most recent call last):
                  File "/lib/python2.7/site-packages/hatohol/haplib.py", line 1123, in __poll_in_try_block
                    self.poll()
                  File "/usr/libexec/hatohol/hap2/hatohol/hap2_zabbix_api.py", line 156, in poll
                    self.make_sure_token()
                  File "/usr/libexec/hatohol/hap2/hatohol/hap2_zabbix_api.py", line 48, in make_sure_token
                    assert ms_info is not None
                AssertionError
python[20594]: hap2_zabbix_api.py:164 hatohol.hap2_zabbix_api:hap2_zabbix_api.py:Poller: [20594]: [ERROR] Polling: aborted.
```

As a result, the message ```Plugin Error: <type 'exceptions.AssertionError'>,``` is output continue.
I think the error message which is output in #2341 is fixed, so we can merge the code for the moment.
And, we need to create new issue related above message if this Pull Request is merged.

**Comment by Mnakagawa** [comment]
HAP2  gets a monitoring server info(ex. polling time, zabbix api URL) from Hatohol server when starting.
The assertion error is caused by the monitoring server info is empty.

So, the problem has no relation to this PR.

> we need to create new issue related above message

Yes. Please create it:+1:

**Pull request merged**
