### PR TITLE
[CentOS 7] Homologize to make rpm for centos7

### PR DESCRIPTION
**Pull request by Mnakagawa**

### CODE REVIEW

**Comment by bynnchapu** [comment]
I have a question.
We can delete COPYING.GPLv3 file, can't we?

**Comment by bynnchapu** [comment]
> We can't delete COPYING.GPLv3 file, can we?

Please see this sentence:
> This version of the GNU Lesser General Public License incorporates
> the terms and conditions of version 3 of the GNU General Public
> License, supplemented by the additional permissions listed below.

**Comment by ashie** [comment]
> Please see this sentence:

You mean COPYING.GPLv3 is needed (shouldn't delete it), don't you?

**Comment by bynnchapu** [comment]
> You mean COPYING.GPLv3 is needed (shouldn't delete it), don't you?

Yes.
I confirmed about this to @yoshfuji san.

**Pull request closed without merging**
