### PR TITLE
Put empty contents

### PR DESCRIPTION
**Pull request by Mnakagawa**
When hap2 get request(ex. item, history) and monitoring target does not have data, HAP2 does not return nothing.
So, request become timeout. After apply this PR, request does not become by HAP2 return empty list(items, histories).

### CODE REVIEW

**Comment by cosmo0920** [comment]
Works fine.
Is there a possibility to write test to verify this behavior?

**Comment by Mnakagawa** [comment]
The possible is not nothing....probablly.
Because, the function output does not nearly changed .

**Comment by cosmo0920** [comment]
Several hap2 test cases are failing: https://travis-ci.org/project-hatohol/hatohol/jobs/142346783#L3996
Could you fix them?

**Comment by cosmo0920** [comment]
Only applying #2359 should break graph feature.
We have to apply this change ASAP after passing HAP2 tests.

**Comment by Mnakagawa** [comment]
ここでsegvが起きると思われる。別PRで修正予定。
https://github.com/project-hatohol/hatohol/blob/master/server/src/DBTablesMonitoring.cc#L2878
```
auto firstItem = *begin(itemInfoList);
```

テストは今ちょっと余裕がないので，しばしお待ちを

**Comment by cosmo0920** [comment]
@Mnakagawa is busy now. 
For now, we should leave this PR as-is.

**Comment by Mnakagawa** [comment]
I fixed some tests.
Please wait a minutes.

**Comment by Mnakagawa** [comment]
Looks so OK.
I merge it.

**Comment by cosmo0920** [comment]
:tada:

**Pull request merged**
