### PR TITLE
Add a HAPI2.0 transporter implementation RabbitMQConnector.

### PR DESCRIPTION
**Pull request by kz0817**

### CODE REVIEW

**Comment by ashie** [comment]
Hmm, tests concerned with HAPI1 fail on Travis CI:

https://travis-ci.org/project-hatohol/hatohol/jobs/66535752

**Comment by kz0817** [comment]
Ops!
Thank you for the comment.
I'm wondering if we launch both qpidd and rabbitmq-server with different ports, run one of them depending on the test alternatively, or remove (or disable) legacy HatoholArmPluginGate tests.

**Comment by ashie** [comment]
I tried to changing qpid's port by editing /etc/defaults/qpidd:

```
DAEMON_OPTS="--config /etc/qpid/qpidd.conf -p 15672"
```

It works on my environment, but I don't try it on Tranvis CI yet.
And some tests still fail although I changed brokerUrl in DBTablesTest.cc and
default brokerUrl in HatoholArmPluginInterface.cc...

**Comment by kz0817** [comment]
Thank you for the information.
It seems that changing the port of rabbitmq-server is easier.
Currently the number of tests that use the RabbitMQ is small.
However, the package install may fail, because it tries to launch rabbitmq-server with the default port.

**Comment by kz0817** [comment]
> However, the package install may fail, because it tries to launch rabbitmq-server with the default port. 

We can workaround that by putting a configuration file under /etc/rabbitmq/rabbitmq.conf.d before the installation ?

**Comment by kz0817** [comment]
I found the way to use the specified port for the installed rabbitmq-server.
<pre>
# mkdir -p /etc/rabbitmq/rabbitmq.conf.d
# echo RABBITMQ_NODE_PORT=5673 > /etc/rabbitmq/rabbitmq.conf.d/port
# apt-get install rabbitmq-server
</pre>

**Comment by kz0817** [comment]
I'll fix the problem and send it again as an another PR.
So I close this.

**Comment by kz0817** [comment]
TravisCIのRabbitMQ Serverは、なぜかversionが3.4。Ubuntu 12.04 LTSの標準は2.7なんだけど。
Anyway, we have to add settings to change the port for the version of rabbitmq-server.

**Comment by ashie** [comment]
Travisで何かしら対応しているようです。

http://docs.travis-ci.com/user/database-setup/#RabbitMQ

**Pull request closed without merging**
