### PR TITLE
Remove HAP1

### PR DESCRIPTION
**Pull request by cosmo0920**
Related to #1469.

### CODE REVIEW

**Comment by ashie** [comment]
server/test/hapi-test-plugin.cc and server/test/hapi-test-plugin.h are still remained in the repository.

**Comment by ashie** [comment]
Files under client/static/js.plugins/ are still remained.
Is it intentional?

**Comment by cosmo0920** [comment]
Oops! I'll remove them.

**Comment by ashie** [comment]
> Files under client/static/js.plugins/ are still remained.

I'm not sure but some tests in test/browser/test_utils.js may be depend on them.

**Comment by cosmo0920** [comment]
Thanks!

**Pull request merged**
