### PR TITLE
[server] Return HTTP code 200 on login failure. (#1581)

### PR DESCRIPTION
**Pull request by kz0817**
The failure of login to Hatohol Server is not HTTP error.
So we should return Code 200.

### CODE REVIEW

**Comment by kz0817** [comment]
With this patch, the login failure message on Web UI becomes to be shown correctly like

**Comment by cosmo0920** [comment]
:+1:

**Comment by ashie** [comment]
History of changing HTTP status code for login failure:

#1030 : Introduce HTTP error codes
#1194 : Bad Request (400) -> Unauthorized(401)

**Comment by ashie** [comment]
Some tests in testFaceRestUser are failed because they check HTTP status code of "/login".
Could you resolve them?

**Comment by ashie** [comment]
> The failure of login to Hatohol Server is not HTTP error.

That's right.
We should return 200.

FYI:

* 400 Bad Request
    * http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.1
```
The request could not be understood by the server due to malformed syntax. 
```

* 401 Unauthorized
    * http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.2
```
The request requires user authentication. The response MUST include a WWW-Authenticate header field (section 14.47) containing a challenge applicable to the requested resource. 
```

So both of them are unsuitable.

**Comment by kz0817** [comment]
> Some tests in testFaceRestUser are failed because they check HTTP status code of "/login".
Could you resolve them?

I've not checked yet.
I'll do it.

**Comment by kz0817** [comment]
I fixed the broken tests.

**Comment by ashie** [comment]
I confirmed it.
Thanks!

**Comment by kz0817** [comment]
Thank you.
Tonight I'll try to fix the other failed tests on the new infrastructure.

**Pull request merged**
