### PR TITLE
[client] Update Japanese translation

### PR DESCRIPTION
**Pull request by ashie**

### CODE REVIEW

**Comment by cosmo0920** [comment]
I've noticed that this the translation for connection status button is wrongly applied. WTF!

screenshot from 2015-10-23 15 26 27

Otherwise, it looks good to me.

**Comment by ashie** [comment]
Oops.
gettext has "pgettext()" function to solve such issue, and Django implements it.
I'll use it.

**Comment by ashie** [comment]
I fixed it.

**Comment by cosmo0920** [comment]
:+1:

**Pull request merged**
