### PR TITLE
[server][JSONBuilder] Use enumize boolean value in JSONBuilder

### PR DESCRIPTION
**Pull request by cosmo0920**
Use straightforward implementation for `add(const std::string&, bool)` member function causes ambiguous occurrence calling overrode like this:

```log
ZabbixAPI.cc: In member function 'SoupMessage* ZabbixAPI::queryEvent(uint64_t, uint64_t, HatoholError&)':
ZabbixAPI.cc:687:19: error: call of overloaded 'add(const char [3], int)' is ambiguous
  agent.add("id", 1);
                   ^
ZabbixAPI.cc:687:19: note: candidates are:
In file included from ZabbixAPI.h:28:0,
                 from ZabbixAPI.cc:24:
JSONBuilder.h:37:7: note: void JSONBuilder::add(const string&, const string&) <near match>
  void add(const std::string &member, const std::string &value);
       ^
JSONBuilder.h:37:7: note:   no known conversion for argument 2 from 'int' to 'const string& {aka const std::basic_string<char>&}'
JSONBuilder.h:38:7: note: void JSONBuilder::add(const string&, gint64)
  void add(const std::string &member, gint64 value);
       ^
JSONBuilder.h:39:7: note: void JSONBuilder::add(const string&, bool)
  void add(const std::string &member, bool value);
       ^
```

So, I defined enum to represent boolean value for JSON and use it.

Ideally speaking, this situation is suitable to use sum type like Scala:

```scala
sealed trait JSONBoolean
case class JSONTrue() extends JSONBoolean
case class JSONFalse() extends JSONBoolean

def sumType(value: JSONBoolean): String = value match {
  case JSONTrue() => "True"
  case JSONFalse() => "False"
}

sumType(new JSONTrue())
// => res0: String = True

sumType(new JSONFalse())
// => res1: String = False
```

But C++ does not have sum type, then I use `enum` to partially emulate sum type behavior.

### CODE REVIEW

**Comment by kou** [comment]
Why don't you define `add(const char *, const int)` for `agent.add("id", 1);`?

**Comment by cosmo0920** [comment]
`add(const char *, const int)` conflicts `add(const std::string&, gint64)`.

**Comment by cosmo0920** [comment]
This phenomenon is cased by C++'s implicit type conversion .

**Comment by kou** [comment]
> `add(const char *, const int)` conflicts `add(const std::string&, gint64)`.

Really? I don't know much about C++ but Hatohol with the following patch can be buildable. Is it wrong program in C++?

```diff
diff --git a/server/common/JSONBuilder.cc b/server/common/JSONBuilder.cc
index 21211a4..232bd7d 100644
--- a/server/common/JSONBuilder.cc
+++ b/server/common/JSONBuilder.cc
@@ -90,12 +90,36 @@ void JSONBuilder::add(const string &member, const string &value)
 	json_builder_add_string_value(m_builder, value.c_str());
 }
 
+void JSONBuilder::add(const string &member, int value)
+{
+	json_builder_set_member_name(m_builder, member.c_str());
+	json_builder_add_int_value(m_builder, value);
+}
+
 void JSONBuilder::add(const string &member, gint64 value)
 {
 	json_builder_set_member_name(m_builder, member.c_str());
 	json_builder_add_int_value(m_builder, value);
 }
 
+void JSONBuilder::add(const string &member, guint32 value)
+{
+	json_builder_set_member_name(m_builder, member.c_str());
+	json_builder_add_int_value(m_builder, value);
+}
+
+void JSONBuilder::add(const string &member, size_t value)
+{
+	json_builder_set_member_name(m_builder, member.c_str());
+	json_builder_add_int_value(m_builder, value);
+}
+
+void JSONBuilder::add(const string &member, bool value)
+{
+	json_builder_set_member_name(m_builder, member.c_str());
+	json_builder_add_boolean_value(m_builder, value);
+}
+
 void JSONBuilder::add(const gint64 value)
 {
 	json_builder_add_int_value(m_builder, value);
@@ -105,15 +129,3 @@ void JSONBuilder::add(const string &value)
 {
 	json_builder_add_string_value(m_builder, value.c_str());
 }
-
-void JSONBuilder::addTrue(const string &member)
-{
-	json_builder_set_member_name(m_builder, member.c_str());
-	json_builder_add_boolean_value(m_builder, TRUE);
-}
-
-void JSONBuilder::addFalse(const string &member)
-{
-	json_builder_set_member_name(m_builder, member.c_str());
-	json_builder_add_boolean_value(m_builder, FALSE);
-}
diff --git a/server/common/JSONBuilder.h b/server/common/JSONBuilder.h
index 4386004..6689920 100644
--- a/server/common/JSONBuilder.h
+++ b/server/common/JSONBuilder.h
@@ -35,11 +35,13 @@ public:
 	void startArray(const std::string &member);
 	void endArray(void);
 	void add(const std::string &member, const std::string &value);
+	void add(const std::string &member, int value);
 	void add(const std::string &member, gint64 value);
+	void add(const std::string &member, guint32 value);
+	void add(const std::string &member, size_t value);
+	void add(const std::string &member, bool value);
 	void add(const gint64 value);
 	void add(const std::string &value);
-	void addTrue(const std::string &member);
-	void addFalse(const std::string &member);
 	void addNull(const std::string &member);
 
 private:
diff --git a/server/common/ZabbixAPI.cc b/server/common/ZabbixAPI.cc
index abbb09e..6fdc8aa 100644
--- a/server/common/ZabbixAPI.cc
+++ b/server/common/ZabbixAPI.cc
@@ -731,7 +731,7 @@ SoupMessage *ZabbixAPI::queryTrigger(HatoholError &queryRet, int requestSince)
 	if (requestSince > 0)
 		agent.add("lastChangeSince", requestSince);
 	agent.add("selectHosts", "refer");
-	agent.addTrue("active");
+	agent.add("active", true);
 	agent.endObject();
 
 	agent.add("auth", m_impl->authToken);
@@ -758,7 +758,7 @@ SoupMessage *ZabbixAPI::queryTriggerExpandedDescription(HatoholError &queryRet,
 		agent.add("lastChangeSince", requestSince);
 	agent.add("expandDescription", 1);
 	agent.add("selectHosts", "refer");
-	agent.addTrue("active");
+	agent.add("active", true);
 	agent.endObject(); //params
 
 	agent.add("auth", m_impl->authToken);
@@ -778,7 +778,7 @@ SoupMessage *ZabbixAPI::queryItem(HatoholError &queryRet)
 	agent.startObject("params");
 	agent.add("output", "extend");
 	agent.add("selectApplications", "refer");
-	agent.addTrue("monitored");
+	agent.add("monitored", true);
 	agent.endObject(); // params
 
 	agent.add("auth", m_impl->authToken);
@@ -827,7 +827,7 @@ SoupMessage *ZabbixAPI::queryHost(HatoholError &queryRet)
 	agent.startObject("params");
 	agent.add("output", "extend");
 	agent.add("selectGroups", "refer");
-	agent.addTrue("monitored_hosts");
+	agent.add("monitored_hosts", true);
 	agent.endObject(); // params
 
 	agent.add("auth", m_impl->authToken);
@@ -845,7 +845,7 @@ SoupMessage *ZabbixAPI::queryGroup(HatoholError &queryRet)
 	agent.add("method", "hostgroup.get");
 
 	agent.startObject("params");
-	agent.addTrue("real_hosts");
+	agent.add("real_hosts", true);
 	agent.add("output", "extend");
 	agent.add("selectHosts", "refer");
 	agent.endObject(); //params
diff --git a/server/src/FaceRest.cc b/server/src/FaceRest.cc
index defff66..5578a48 100644
--- a/server/src/FaceRest.cc
+++ b/server/src/FaceRest.cc
@@ -508,10 +508,7 @@ void FaceRest::handlerTest(ResourceHandler *job)
 	FaceRest::ResourceHandler::addHatoholError(
 	  agent, HatoholError(HTERR_OK));
 	const bool testMode = ConfigManager::getInstance()->isTestMode();
-	if (testMode)
-		agent.addTrue("testMode");
-	else
-		agent.addFalse("testMode");
+	agent.add("testMode", testMode);
 
 	if (string(job->m_path) == "/test" &&
 	    string(job->m_message->method) == "POST")
diff --git a/server/src/RestResourceHost.cc b/server/src/RestResourceHost.cc
index 1f7f10b..ab70a7a 100644
--- a/server/src/RestResourceHost.cc
+++ b/server/src/RestResourceHost.cc
@@ -645,10 +645,7 @@ void RestResourceHost::handlerGetEvent(void)
 	addHatoholError(agent, HatoholError(HTERR_OK));
 	// TODO: should use transaction to avoid conflicting with event list
 	agent.add("lastUnifiedEventId", getLastUnifiedEventId(this));
-	if (addIncidents)
-		agent.addTrue("haveIncident");
-	else
-		agent.addFalse("haveIncident");
+	agent.add("haveIncident", addIncidents);
 	agent.startArray("events");
 	EventInfoListIterator it = eventList.begin();
 	for (size_t i = 0; it != eventList.end(); ++i, ++it) {
diff --git a/server/src/RestResourceServer.cc b/server/src/RestResourceServer.cc
index 5fc6914..51bd273 100644
--- a/server/src/RestResourceServer.cc
+++ b/server/src/RestResourceServer.cc
@@ -156,10 +156,7 @@ static void addServers(FaceRest::ResourceHandler *job, JSONBuilder &agent,
 		if (pluginIt->id != INVALID_ARM_PLUGIN_INFO_ID) {
 			const bool passiveMode =
 			  (pluginIt->path == HatoholArmPluginGate::PassivePluginQuasiPath);
-			if (passiveMode)
-				agent.addTrue("passiveMode");
-			else
-				agent.addFalse("passiveMode");
+			agent.add("passiveMode", passiveMode);
 			agent.add("brokerUrl", pluginIt->brokerUrl);
 			agent.add("staticQueueAddress",
 			          pluginIt->staticQueueAddress);
@@ -169,10 +166,7 @@ static void addServers(FaceRest::ResourceHandler *job, JSONBuilder &agent,
 			          pluginIt->tlsKeyPath);
 			agent.add("tlsCACertificatePath",
 			          pluginIt->tlsCACertificatePath);
-			if (pluginIt->tlsEnableVerify)
-				agent.addTrue("tlsEnableVerify");
-			else
-				agent.addFalse("tlsEnableVerify");
+			agent.add("tlsEnableVerify", pluginIt->tlsEnableVerify);
 		}
 		agent.endObject();
 	}
```

**Comment by cosmo0920** [comment]
> Really? I don't know much about C++ but Hatohol with the following patch can be buildable. Is it wrong program in C++?

This is not wrong. It is correct C++ program.

**Comment by cosmo0920** [comment]
@ashie and I discussed F2F, this is undesirable to add `JSONBuilder::add` overlorded API.
Because `addTrue` and `addFalse` are represent by name to set Boolean value in JSON, and perhaps users want to represent to set Boolean value explicitly.

And adding `JSONBuilder::add` overload for boolean, when users mistake second argument value, users got unexpected result like this:

*  users want to call `add(const std::string, bool)` overload

But, users mistype as follows:

```cpp
agent.add("boolean expected", 2)
```

Then, `add(const std::string, gint64)` overload called.
This result is unexpected effects by implementing `add(const std::string, bool)` overload.

So, I close this PR.

**Comment by kou** [comment]
FYI: With the current Hatohol, `agent.add("int expected", true)` is processed by `add(const std::string, gint64)`. It may be a pitfall.

**Comment by cosmo0920** [comment]
Oh..., it is undesirable result....

**Pull request closed without merging**
