### PR TITLE
[hap2] Use WatchFileHandler for logging.

### PR DESCRIPTION
**Pull request by kz0817**
WatchFileHandler supports change of the target log file,
which typically happens when logroate is used.

### CODE REVIEW

**Comment by ashie** [comment]
It's not for master, it's for work-for-splitting-#2370, isn't it?
I changed the base branch to work-for-splitting-#2370...

**Comment by kz0817** [comment]
This patch may break a test.
I'll look into it.
So please wait for the merge.

ERROR: test_private_set_ms_info (TestHaplib.BasePoller)

**Comment by cosmo0920** [comment]
I've created a new label which is "Do not merge".
When your task is completed, please remove this label.

**Comment by kz0817** [comment]
I could reproduce the error on my computer.
It occurred on this branch, but didn't on work-for-splitting-#2370.
That is, the patch in this PR has a problem.

**Comment by kz0817** [comment]
I fixed a potential problem and pushed it in the branch for this PR because it's related to this PR's patches. Please resume a review.

**Pull request merged**
