### PR TITLE
Dynamic change action dialog severity label and Fix invalid label

### PR DESCRIPTION
**Pull request by Mnakagawa**
Related: #2254

### CODE REVIEW

**Comment by Mnakagawa** [comment]
> if (!(severity === null))

The above line has jshint error.
But, I do not resolve it.
Do you know solution?

**Comment by Mnakagawa** [comment]
```
~/hatohol$ jshint client/static/js/hatohol_add_action_dialog.js 
client/static/js/hatohol_add_action_dialog.js: line 467, col 10, Confusing use of '!'.
```

**Comment by cosmo0920** [comment]
How about this one?

```diff
diff --git a/client/static/js/hatohol_add_action_dialog.js b/client/static/js/ha
tohol_add_action_dialog.js
index dd7a306..56a528d 100644
--- a/client/static/js/hatohol_add_action_dialog.js
+++ b/client/static/js/hatohol_add_action_dialog.js
@@ -464,7 +464,7 @@ var HatoholAddActionDialog = function(changedCallback, incid
entTrackers, actionD
       hatoholErrorMsgBox(gettext("Unknown severity: ") + severity);
       break;
     }
-    if (!(severity === null)) {
+    if (severity !== null) {
       $("#selectTriggerSeverityCompType").css("visibility","visible");
     }
   }
```

**Comment by Mnakagawa** [comment]
Thank you!

**Comment by cosmo0920** [comment]
Awesome! XD
Let's wait for CI results.

**Comment by Mnakagawa** [comment]
Thanks!

**Pull request merged**
