### PR TITLE
Fix config button design in event page

### PR DESCRIPTION
**Pull request by BlueSkyDetector**
It's for fixing #1908.

### CODE REVIEW

**Comment by cosmo0920** [comment]
I've confirmed that new Web design is applied in Event Console page like this:

screenshot from 2016-01-12 11 53 21

But translation for this button's word is not applied. Is this expected?

**Comment by BlueSkyDetector** [comment]
Even after executing "make .po.mo", the translation is not applied?

**Comment by BlueSkyDetector** [comment]
Sorry, I needed to include *.po files.

**Comment by cosmo0920** [comment]
> Even after executing "make .po.mo", the translation is not applied?

No, translation is not applied.
"Config" translation is disabled on po for this branch. Perhaps, you should run update-po in client root directory and apply translation for Config button.

**Comment by cosmo0920** [comment]
:+1:

**Comment by ashie** [comment]
Oops, it should be merge by the release manager (@Mnakagawa) because it's a pull request against
a "releng" branch.

**Comment by cosmo0920** [comment]
Oh..., I forgot to about it....

**Pull request merged**
