### PR TITLE
Add extended info for monitoring server

### PR DESCRIPTION
**Pull request by ashie**
Because it's required in HAPI 2.0:

https://github.com/project-hatohol/HAPI-2.0-Specification

### CODE REVIEW

**Comment by Mnakagawa** [comment]
Thank you :+1:

**Comment by kz0817** [comment]
On my environment, a test failed with the following message.
As the message shows, the row size might be too large.
I think that the maximum length depends on the storage engine though.
However, the size of both "base_url" and "extended_info" are 32767.
base_url should be short. 

<pre>
testMain:
  testMain::test_daemonize:                             [INFO] <main.cc:217> started hatohol server: ver. 15.06_dev
[CRIT] <main.cc:175> Failed to create a database object. This program is aborted. Reason: <DBAgentMySQL.cc:646> Failed to query: CREATE TABLE servers (id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,type INT(11) NOT NULL,hostname VARCHAR(255) NOT NULL,ip_address VARCHAR(255) NOT NULL,nickname VARCHAR(255) NOT NULL,port INT(11) NOT NULL,polling_interval_sec INT(11) NOT NULL,retry_interval_sec INT(11) NOT NULL,user_name VARCHAR(255) NOT NULL,password VARCHAR(255) NOT NULL,db_name VARCHAR(255) NOT NULL,base_url VARCHAR(32767),extended_info VARCHAR(32767)): (1118) Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. You have to change some columns to TEXT or BLOBs
</pre>

**Comment by ashie** [comment]
In HAPI2.0, it's defined as String255:

https://github.com/project-hatohol/HAPI-2.0-Specification#getmonitoringserverinfomethod

it would be enough in most cases.
I'll shorten it.

**Comment by kz0817** [comment]
It's topic for the HAPI 2.0 spec. though. 255 characters for URL may be a little small for some case.
What does everyone think ?

**Comment by ashie** [comment]
> It's topic for the HAPI 2.0 spec. though. 255 characters for URL may be a little small for some case.
> What does everyone think ?

I've filed an issue for the spec:

https://github.com/project-hatohol/HAPI-2.0-Specification/issues/5

**Comment by ashie** [comment]
I'll modify the max length of URL to 2048 then send another pull request.

**Pull request closed without merging**
