### PR TITLE
[hap2][client][zabbix] Implement get{Top,Maps,ItemGraph}URL()

### PR DESCRIPTION
**Pull request by ashie**
And simplify getTopURL() in nagios.js.

(Remove problematic codes in #1480)

### CODE REVIEW

**Comment by ashie** [comment]
> We should use extendInfo in HAP2 Nagios....

In the current implementation, users are required to enter raw JSON because there is no way to
render input form for it. I want to add a mechanism to do it.

**Comment by cosmo0920** [comment]
Do improving HAP2 nagios implementation is another pull request?

**Comment by cosmo0920** [comment]
Merged!

**Comment by ashie** [comment]
Thanks!

**Pull request merged**
