### PR TITLE
[Experimental][client][server] set arbitrary http status code

### PR DESCRIPTION
**Pull request by cosmo0920**
This pull request contains *experimental feature* for improving testability, as follows:

* `FaceRest::ResourceHandler::replyJSONData` and `FaceRest::ResourceHandler::replyError` can accept arbitrary HTTP status code such as **401 (Unauthorized)**, **403 (Forbidden)**, ... and so on.
  * Default HTTP status is **200 (OK)**.
* Hatohol client can handle non-200 response from Hatohol server.
* Try to send response which is non-200 status code in user authentication.

Here is failing user authentication senario:

 When failing to user authenticate, Hatohol server send **401 (Unauthorized)** response to Hatohol client(WebUI). Hatohol client just passes through Hatohol server response. Nevertheless non-200 status response from Hatohol server.
 Finally, user's browser receives **401 (Unauthorized)** response from Hatohol client(WebUI).

### CODE REVIEW

**Comment by cosmo0920** [comment]
This pull request is part of work for comment: https://github.com/project-hatohol/hatohol/pull/1014#issuecomment-75208177
(This is not registered in issue tracker yet.)

**Comment by cosmo0920** [comment]
I've confirmed both Travis ci push and pr tests passed.

**Comment by ashie** [comment]
Thanks!

**Comment by cosmo0920** [comment]
Thank you for merging!

**Pull request merged**
