### PR TITLE
[client][EventsView] Add UI for creating filter definitions (WIP)

### PR DESCRIPTION
**Pull request by ashie**
Revice #1583 

I added UI to define filters.
It's not completed yet.

* "Default filter" setting isn't implemented yet
* No one uses created filters yet.

It's just only create filter settings (JSON) and store them to DB.

Note that this page isn't shown by default.
You can see it by the following query:

http://localhost/ajax_events?devel=true

filter-settings

### CODE REVIEW

**Comment by kz0817** [comment]
A test failed. Can we ignore it ?
<pre>
  1) EventsViewConfig "before each" hook:

     Uncaught Error: expected undefined to equal 'none' (http://localhost:8000/test/expect.js:102)
</pre>

**Comment by kz0817** [comment]
I built this branch and ran. Different from the screen you attached in this PR, a tab was not shown on the dialog as the following picture. Is this correct ?
event-consle-setting

**Comment by ashie** [comment]
> A test failed. Can we ignore it ?

No. I'll investigate it.

**Comment by ashie** [comment]
> I built this branch and ran. Different from the screen you attached in this PR

Could you add "?devel=true" to the URL?

> Note that this page isn't shown by default.
> You can see it by the following query:
> 
> http://localhost/ajax_events?devel=true

**Comment by kz0817** [comment]
> Could you add "?devel=true" to the URL?

Oh. I missed it. OK. I confirmed that a tab is shown.

**Comment by ashie** [comment]
> A test failed. Can we ignore it ?

I fixed it (although it's an issue in #1584).
Please review again.

**Comment by ashie** [comment]
Thanks!

**Pull request merged**
