### PR TITLE
Modified the query language (issue #1052)

### PR DESCRIPTION
**Pull request by o-wakabayashi**
Message string to the user for confirmation from the UI, when performing a delete or reload.

### CODE REVIEW

**Comment by bynnchapu** [comment]
Please update header of po files.

**Comment by o-wakabayashi** [comment]
oh... yes, corresponding to it.

**Comment by ashie** [comment]
Thanks!

**Comment by o-wakabayashi** [comment]
thank you for merged.

2015-03-06 10:22 GMT+09:00 Takuro Ashie <notifications@github.com>:

**Pull request merged**
